# Generated by Django 5.0.6 on 2024-06-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150, verbose_name='название')),
                ('model', models.TextField(max_length=150, unique=True, verbose_name='модель')),
                ('release_data', models.DateTimeField(auto_now_add=True, verbose_name='дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150, verbose_name='название')),
                ('level', models.CharField(choices=[(0, 'завод'), (1, 'розничная сеть'), (2, 'индивидуальный предприниматель')], default=0, verbose_name='уровень')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='электронная почта')),
                ('country', models.TextField(max_length=150, verbose_name='страна')),
                ('city', models.TextField(max_length=150, verbose_name='город')),
                ('street', models.TextField(max_length=150, verbose_name='улица')),
                ('house_number', models.TextField(max_length=150, verbose_name='номер дома')),
                ('debt', models.TextField(verbose_name='задолженность перед поставщиком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('products', models.ManyToManyField(db_index=True, to='online_platform.product', verbose_name='продукты')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
            },
        ),
    ]
