# Generated by Django 5.0.6 on 2024-06-15 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='level',
            field=models.CharField(choices=[('завод', 0), ('розничная сеть', 1), ('индивидуальный предприниматель', 2)], default=0, verbose_name='уровень'),
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_platform.supplier', verbose_name='Поставщик')),
            ],
        ),
    ]
