# Generated by Django 5.0.6 on 2024-06-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_platform', '0002_alter_supplier_level_network'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'сеть', 'verbose_name_plural': 'сети'},
        ),
        migrations.AddField(
            model_name='network',
            name='name',
            field=models.CharField(default='тест', max_length=150, verbose_name='название'),
        ),
    ]
