# Generated by Django 5.0.6 on 2024-06-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_platform', '0004_alter_network_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='debt',
        ),
        migrations.AddField(
            model_name='network',
            name='supplier_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='задолженность перед поставщиком'),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='название'),
        ),
    ]
