# Generated by Django 5.0.6 on 2024-06-15 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_platform', '0005_remove_supplier_debt_network_supplier_debt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='электронная почта')),
                ('country', models.TextField(max_length=150, verbose_name='страна')),
                ('city', models.TextField(max_length=150, verbose_name='город')),
                ('street', models.TextField(max_length=150, verbose_name='улица')),
                ('house_number', models.TextField(max_length=150, verbose_name='номер дома')),
            ],
        ),
        migrations.AddField(
            model_name='network',
            name='contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='online_platform.contact', verbose_name='Контакты'),
        ),
    ]
