# Generated by Django 5.0.6 on 2024-06-15 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_platform', '0006_contact_network_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_platform.contact', verbose_name='Контакты'),
        ),
    ]
